# Generated by Django 5.0.6 on 2024-05-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_presentation_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
