# Generated by Django 5.0.6 on 2024-05-24 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_presentation_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='scientificwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.scientificwork'),
        ),
    ]
