# Generated by Django 5.0.6 on 2024-05-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_presentation_scientificwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='topic',
        ),
    ]
