# Generated by Django 5.0.6 on 2024-05-24 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_presentation_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='scientificwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.scientificwork'),
        ),
    ]
